version: '2'

services:

# not sure if we will need this
# syslog:
# sudo docker run -it -p 5514:514 -v $(pwd)/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf -v $(pwd)/network.log:/var/log/network.log balabit/syslog-ng:latest -edv

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/patterns:/opt/logstash/patterns

    ports:
      - "5140:5140/udp"

    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

# put the nodes on the host network so that source ips are retained
networks:

  elk:
    driver: bridge
